import manifest from "./image-manifest.json";

/**
 * Image resolver. Dimensions come from image-manifest.json (generated by
 * scripts/optimize-images.mjs); alt text and credits are authored here so
 * next/image always gets explicit width/height + meaningful alt.
 */

export interface ResolvedImage {
  src: string;
  width: number;
  height: number;
  alt: string;
  credit?: string;
}

type ManifestEntry = { src: string; width: number; height: number };
const M = manifest as Record<string, ManifestEntry>;

const NOAA = "Image courtesy of NOAA";
const NOAA_OE = "Image courtesy of NOAA Ocean Exploration";
const NOAA_FISHERIES = "Image courtesy of NOAA Fisheries / Ari Halperin";
const NOAA_PL = "Image courtesy of the NOAA Photo Library";
const EPA = "Image courtesy of the U.S. EPA";
const PEXELS = "Photo via Pexels (free licence)";
const CC0 = "Bleached Porites lobata by Francois Seneca (CC0)";

const META: Record<string, { alt: string; credit?: string }> = {
  // Species
  "sp-dumbo-octopus": { alt: "A dumbo octopus hovering in black water, its ear-like fins spread", credit: NOAA },
  "sp-anglerfish": { alt: "A deep-sea anglerfish resting on rock, lit by an ROV", credit: NOAA_OE },
  "sp-tubeworms": { alt: "Giant tubeworms clustered around a hydrothermal vent", credit: NOAA_PL },
  "sp-sea-turtle": { alt: "A green sea turtle gliding through clear blue water", credit: PEXELS },
  "sp-humpback": { alt: "A humpback whale swimming in deep blue open water", credit: PEXELS },
  "sp-sixgill-shark": { alt: "A shark cruising through dark water", credit: PEXELS },
  "sp-crown-of-thorns": { alt: "A crown-of-thorns starfish spread across reef", credit: NOAA },
  "sp-pink-jelly": { alt: "A translucent pink deep-sea jellyfish drifting in open water", credit: NOAA },
  "sp-bamboo-coral": { alt: "A deep-sea coral garden on a seamount", credit: NOAA_OE },
  "sp-rockfish": { alt: "A rockfish sheltering among deep-sea coral", credit: NOAA },
  "sp-red-crab": { alt: "A deep-sea crab beside a sea anemone on the seabed", credit: NOAA },
  "sp-lobe-coral": { alt: "A bleached, stark-white lobe coral colony", credit: CC0 },

  // Incident evidence
  "ev-ghostnet-turtle": { alt: "A green sea turtle entangled in a ball of abandoned fishing net", credit: NOAA_FISHERIES },
  "ev-ghostnet": { alt: "Abandoned fishing nets tangled in murky water", credit: EPA },
  "ev-plastic-bottle": { alt: "A plastic bottle floating below the ocean surface", credit: PEXELS },
  "ev-plastic-dark": { alt: "Plastic bottles floating in dark, polluted water", credit: PEXELS },
  "ev-plastic-shore": { alt: "Plastic waste strewn across a shoreline", credit: PEXELS },
  "ev-bleached": { alt: "A bleached, stark-white coral colony indicating heat stress", credit: CC0 },

  // Hero / section
  "hero-main": { alt: "Shafts of light falling through dark teal ocean water", credit: PEXELS },
  "hero-poster": { alt: "Shafts of light falling through dark teal ocean water", credit: PEXELS },
  "hero-rov": { alt: "An ROV descending toward a deep-ocean fault wall", credit: NOAA_OE },
  "hero-jelly": { alt: "A jellyfish suspended in the deep dark ocean", credit: PEXELS },
  "hero-bubbles": { alt: "Bubbles rising toward the sunlit sea surface", credit: PEXELS },
  "hero-submerged": { alt: "Light beams breaking through water over submerged forms", credit: PEXELS },

  // Tech / how-it-works
  "tech-auv": { alt: "An autonomous underwater vehicle being deployed from a research vessel", credit: NOAA_OE },
  "tech-rov-benthic": { alt: "An ROV documenting benthic communities on the seafloor", credit: NOAA_OE },
  "tech-sonar": { alt: "A multibeam sonar bathymetry map of the seafloor", credit: NOAA_OE },
  "tech-rov-launch": { alt: "An ROV prepared for launch on a ship deck", credit: NOAA_OE },
};

const FALLBACK: ResolvedImage = {
  src: "/images/hero-main.jpg",
  width: 2000,
  height: 1334,
  alt: "Deep ocean water",
};

export function getImage(key: string): ResolvedImage {
  const dims = M[key];
  const meta = META[key];
  if (!dims) return FALLBACK;
  return {
    src: dims.src,
    width: dims.width,
    height: dims.height,
    alt: meta?.alt ?? "Deep ocean imagery",
    credit: meta?.credit,
  };
}

export const SPECIES_IMAGE_KEYS = Object.keys(META).filter((k) => k.startsWith("sp-"));
export const EVIDENCE_IMAGE_KEYS = Object.keys(META).filter((k) => k.startsWith("ev-"));
